import store from "./store";

export type { RootState, StoreDispatch } from "./store";

export {
  setCurrentIndex,
  setSlideRatio,
  zoomIn,
  zoomOut,
  setContentSelectedTab,
  setContentOrientation,
  setTitle,
  setTitleFontSize,
  toggleSubTitle,
  setSubTitle,
  toggleTitle,
  setDescription,
  setDescriptionFontSize,
  toggleDescription,
  setCTAText,
  toggleCTAButton,
  setImageSrc,
  toggleImage,
  setImageOpacity,
  setImageBackgroundPosition,
  setImageBackgroundSize,
  toggleCustomFontsEnabled,
  setPrimaryFont,
  setSecondaryFont,
  setContentFontSize,
  setContentFontTextAlignment,
  toggleCustomColors,
  setBackgroundColor,
  setTextColor,
  setAccentColor,
  setColors,
  toggleAlternateSlideColors,
  setBackgroundId,
  toggleBrandShowInIntroSlide,
  toggleBrandShowInOutroSlide,
  toggleBrandShowInRegularSlide,
  setBrandName,
  toggleBrandName,
  setBrandHandle,
  toggleBrandHandle,
  setBrandProfileSrc,
  toggleBrandProfile,
  setOverlayColor,
  setOverlayOpacity,
  toggleOverlayFadeCorner,
  setCornerElementId,
  setCornerElementOpacity,
  toggleShowWaterMark,
  toggleHideIntroSlide,
  toggleHideOutroSlide,
  toggleHideCounter,
  setIntroSlideArrowText,
  toggleIntroSlideArrow,
  setRegularSlideArrowText,
  toggleRegularSlideArrow,
  toggleArrowText,
  setArrowId,
} from "./carousels.slice";

export default store;
