import type { Metadata } from "next";
import "./globals.css";
import { RootLayout } from "@/components";

export const metadata: Metadata = {
  title: "Carousel Web",
  description: "Generated by create next app",
};

export default RootLayout